# SyncShelf Deno CI/CD Workflow
# This workflow sets up Deno, runs linting, formatting checks, and tests.
# For more information, see: https://github.com/denoland/setup-deno

name: SyncShelf Deno CI

on:
  push:
    branches: ["main"]  # Trigger workflow on pushes to main branch
  pull_request:
    branches: ["main"]  # Trigger workflow on pull requests targeting main branch

permissions:
  contents: read  # Permissions required to check out the code

jobs:
  test:
    runs-on: ubuntu-latest  # Environment for the job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checkout the code from the repository

      - name: Setup Deno
        uses: denoland/setup-deno@v1  # Install Deno
        with:
          deno-version: v1.x  # Use the latest stable version of Deno

      - name: Verify Code Formatting
        run: deno fmt --check  # Check if the code is properly formatted

      - name: Run Linter
        run: deno lint  # Lint the code for potential issues

      - name: Run Tests
        run: deno test -A  # Run all tests with all permissions

      - name: Build Documentation
        run: deno run --allow-read --allow-write build_docs.ts  # Command to build project documentation, adjust if needed

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/main'  # Only deploy if the main branch is updated
        run: deno deploy --prod # Command for deployment, adjust as necessary
